brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoDeleteView,
    TodoDetailView,
    TodoListView,
    TodoCreateView,
    TodoUpdateView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="update_todolist"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete_todolist"),
    path("items/create/", TodoItemCreateView.as_view(), name="create_todoitem"),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="update_todoitem",
    ),
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.task

todos/views.py
# from django.shortcuts import render

from django.urls import reverse_lazy

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from todos.models import TodoItem, TodoList

# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = "/todos/"


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.list.id])

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do Lists</title>
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>

todos/templates/items/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Create a new item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/items/edit.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Update item</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>"Create a new list"</h1>
        <form method="POST">
            {% csrf_token %}
            Name: <input type="text" name="name">
            <button>Create</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Are you sure?</h1>
        <form method="post">
            {% csrf_token %}
            <button>Delete</button>
        </form>
    </div>
</main>
{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>{{ todolist.name }}</h1>
        <h2>Tasks</h2>
        <div>
            <p>
                <a href="{% url 'update_todolist' todolist.id %}">Edit</a>
                <a href="{% url 'delete_todolist' todolist.id %}">Delete</a>
            </p>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for item in todolist.items.all %}
                <tr>
                    <td><a href="{% url 'update_todoitem' item.id %}">{{ item.task }}</a></td>
                    <td>{{ item.due_date|date:"M d, Y" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}

todos/templates/todos/edit.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>Update list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Update</button>
        </form>
    </div>
</main>

{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <h1>My Lists</h1>
        <div>
            <p><a href="{% url 'create_todolist' %}">Create a new list</a></p>
            <p><a href="{% url 'create_todoitem' %}">Create a new item</a></p>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Items</th>
                </tr>
            </thead>
            <tbody>
                {% for list in todolist_list %}
                <tr>
                    <td>
                        <a href="{% url 'show_todolist' list.id %}">{{ list.name }}</a>
                    </td>
                    <td>{{ list.items.all|length }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock content %}